services:
  django-paralleltext:
    secrets:
      - "DJANGO_SECRET_KEY"
    environment:
      DJANGO_SECRET_KEY: /run/secrets/DJANGO_SECRET_KEY
    image: "nkuusik/django-paralleltext:latest"
    ports:
      - "8000:8000"

secrets:
  DJANGO_SECRET_KEY:
    file: "$HOME/django_secrets/DJANGO_SECRET_KEY"