# Generated by Django 5.0.7 on 2024-07-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textparser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
